name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write   
  contents: read    
  checks: read

jobs:
  setup-build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'project-owner-access@mobia-mission-aaron.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/1039028925758/locations/global/workloadIdentityPools/mobia-mission-pool/providers/unseenservant-github'


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t us-east1-docker.pkg.dev/mobia-mission-aaron/app-mobia/mobiaapp:latest ./build

    - name: Push Docker image
      if: success()
      run: |
        docker push us-east1-docker.pkg.dev/mobia-mission-aaron/app-mobia/mobiaapp:latest
