name: Apply Terraform

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VERSION: 1.7.2

permissions:
  id-token: write   
  contents: read    
  checks: read

jobs:
  terraform-apply-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'project-owner-access@mobia-mission-aaron.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/1039028925758/locations/global/workloadIdentityPools/mobia-mission-pool/providers/unseenservant-github'

    - name: Terraform Init GKE
      run: terraform -chdir="01-gke-infra" init

    - name: Terraform Apply GKE
      run: terraform -chdir="01-gke-infra" apply -var-file=prod.tfvars -auto-approve

  terraform-apply-app:
    runs-on: ubuntu-latest
    needs: terraform-apply-gke

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'project-owner-access@mobia-mission-aaron.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/1039028925758/locations/global/workloadIdentityPools/mobia-mission-pool/providers/unseenservant-github'

    - name: Terraform Init APP
      run: terraform -chdir="02-k8s-deploy" init

    - name: Terraform Apply APP
      run: terraform -chdir="02-k8s-deploy" apply -var-file=prod.tfvars -auto-approve
